### ISSUE TITLE
While installing Saleor, throwing ImportError : No module named parse

### ISSUE THREAD

**Issue by prashante114** [mirumee/saleor#1024]
Hi,
I have installed Saleor as per the instructions given in 

After installation, when I run ```python manage.py migrate``` , it is throwing below error :
``` 
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/django/utils/autoreload.py", line 226, in wrapper
    fn(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/django/core/management/commands/runserver.py", line 113, in inner_run
    autoreload.raise_last_exception()
  File "/usr/local/lib/python2.7/dist-packages/django/utils/autoreload.py", line 249, in raise_last_exception
    six.reraise(*_exception)
  File "/usr/local/lib/python2.7/dist-packages/django/utils/autoreload.py", line 226, in wrapper
    fn(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/django/__init__.py", line 27, in setup
    apps.populate(settings.INSTALLED_APPS)
  File "/usr/local/lib/python2.7/dist-packages/django/apps/registry.py", line 108, in populate
    app_config.import_models(all_models)
  File "/usr/local/lib/python2.7/dist-packages/django/apps/config.py", line 199, in import_models
    self.models_module = import_module(models_module_name)
  File "/usr/lib/python2.7/importlib/__init__.py", line 37, in import_module
    __import__(name)
  File "/usr/local/lib/python2.7/dist-packages/social_django/models.py", line 10, in <module>
    from .storage import DjangoUserMixin, DjangoAssociationMixin, \
  File "/usr/local/lib/python2.7/dist-packages/social_django/storage.py", line 8, in <module>
    from social_core.storage import UserMixin, AssociationMixin, NonceMixin, \
  File "/usr/local/lib/python2.7/dist-packages/social_core/storage.py", line 12, in <module>
    from openid.association import Association as OpenIdAssociation
  File "/usr/local/lib/python2.7/dist-packages/openid/association.py", line 37, in <module>
    from openid import cryptutil
  File "/usr/local/lib/python2.7/dist-packages/openid/cryptutil.py", line 33, in <module>
    from openid.oidutil import toBase64, fromBase64
  File "/usr/local/lib/python2.7/dist-packages/openid/oidutil.py", line 15, in <module>
    from urllib.parse import urlencode
ImportError: No module named parse


```

Could anyone help me on how to solve this?

**Comment by Kaushik-Roy** [comment]
Do you Have urllib or urllib2 installed ?
use these commands for your python version.
```
apt-get install python-urllib3  # for python 2
apt-get install python3-urllib3 # for python 3
or
pip install urllib3 # for python 2
pip3 install urllib3 # for python 3
```

**Comment by Kaushik-Roy** [comment]
Do you Have urllib installed ?
use these commands for your python version.

```
apt-get install python-urllib3  # for python 2
apt-get install python3-urllib3 # for python 3
or
pip install urllib3 # for python 2
pip3 install urllib3 # for python 3
```

**Comment by szewczykmira** [comment]
I think you have openid for python3 installed. Can you uninstall `python3-openid` and then `pip install python-openid` - this should solve the problem.

**Comment by prashante114** [comment]
@Kaushik-Roy  @szewczykmira 

I tried above commands as per your suggestion, but still facing same error

**Comment by szewczykmira** [comment]
Do you have most recent version of saleor? I see that your fork is 808 commits behind our master branch.

**Comment by prashante114** [comment]
@szewczykmira  I just checked for latest updates from saleor, it is showing "Already up-to-date."

please check below screen-shot and help if I am taking updates from correct repo.

![saleor-pull](https://cloud.githubusercontent.com/assets/16849056/25328970/7154d7e0-28f7-11e7-8d81-d64815e9546b.png)

**Comment by szewczykmira** [comment]
@prashante114 can you run `git remote -v` and show me result?

**Comment by prashante114** [comment]
@szewczykmira 

`origin	https://github.com/mirumee/saleor.git (fetch)
origin	https://github.com/mirumee/saleor.git (push)
`

**Comment by prashante114** [comment]
I followed all steps and installed new Saleor on system 
server is running but throwing following error:

<img width="1237" alt="screen shot 2017-04-26 at 12 40 22 pm" src="https://cloud.githubusercontent.com/assets/16849056/25422397/63de62a6-2a7e-11e7-9ade-a781f5b036da.png">

**Comment by artursmet** [comment]
Hi @prashante114 it looks like there is missing a file in your local version, because the file https://github.com/mirumee/saleor/blob/master/saleor/core/templatetags/markdown.py exists on master branch. Could you check if this file exists in your local copy?

**Comment by prashante114** [comment]
@artursmet I just checked for the file. Yes, It exists in the local copy.

**Comment by Kaushik-Roy** [comment]
please check inside your environment(env) if the markdown exists or not... for me the directory will be 
`env/lib/python3.5/site-packages/makdown `
if not the install using these commands.
pip install markdown
or
easy_install markdown

if the Markdown is existing please try to find the version and compare it to the ` requirements.txt` , if the existing version is different from the listed version in requirements.txt try changing the version on the requirements.txt and run the `pip install -r requrements.txt`

Even i get an `appdirs` version error whenever i try to install saleor in any machine , i change the appdir version from 1.4.0 to 1.4.3 and it works....

even you try something like this !! see what happes...

**Comment by prashante114** [comment]
@Kaushik-Roy  Thank You 
Its working

**Comment by Kaushik-Roy** [comment]
@prashante114 :  welcome ! happy to help.
