### ISSUE TITLE
Yarn run build-assets error

### ISSUE THREAD

**Issue by adrhem** [mirumee/saleor#1164]
Hi there, I am installing a clean distribution of Saleor, but when I run 
`yarn run build-assets` I get the following error:

```
yarn run v1.0.2
$ node ./node_modules/webpack/bin/webpack.js -p
events.js:160
      throw er; // Unhandled error event
      ^

Error: write EPIPE
    at exports._errnoException (util.js:1020:11)
    at WriteWrap.afterWrite (net.js:800:14)
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command..
```

My node version:
`node -v
v6.11.4`

My yarn version
`yarn -v
1.0.2`

**Comment by DonerKebab** [comment]
I ran into the same problem. I fixed it by install phantom.

**Comment by adrhem** [comment]
I still have the same problem. I tried compile on a Mac (Sierra latest) and no problem. I thought that is just a problem with Linux. I use Ubuntu.

**Comment by bellaj** [comment]
resolved if downgraded to V4.*

**Comment by adrhem** [comment]
Thank you @bellaj ! It works!

**Comment by deathping1994** [comment]
@bellaj , downgraded to version v4 of what ?

**Comment by elwoodxblues** [comment]
@bellaj We've switched from Yarn to NPM in the meantime, so this issue is no more valid.
