### ISSUE TITLE
git push heroku master

### ISSUE THREAD

**Issue by mstfmomin** [mirumee/saleor#529]
Hello,

I am trying to deploy the eCommerce site to heroku. 

```
git clone https://github.com/mirumee/saleor.git && cd saleor/ && sudo pip install -r requirements.txt && export SECRET_KEY='mysecretkey' && python manage.py migrate

curl -sL https://deb.nodesource.com/setup_4.x | sudo -E bash - && sudo apt-get install -y nodejs && sudo apt-get install nodejs-legacy

npm install && ./node_modules/.bin/grunt
python manage.py runserver
```

This one works perfectly on local machine. Now I want to push it to heroku. Here what I have used

```
heroku create kakumamu3 --buildpack https://github.com/ddollar/heroku-buildpack-multi.git
 git push heroku master`


```

This one fails. It says:

```
  git push heroku master
 Counting objects: 14143, done.
 Delta compression using up to 4 threads.
  Compressing objects: 100% (4398/4398), done.
  Writing objects: 100% (14143/14143), 4.85 MiB | 424.00 KiB/s, done.
  Total 14143 (delta 9001), reused 14143 (delta 9001)
  remote: Compressing source files... done.
  remote: Building source:
  remote: 
  remote: ----- Fetching set buildpack https://github.com/trailheadlabs/heroku-buildpack-multi.git... done
  remote: 
  remote:  !     Push rejected, failed to detect set buildpack https://github.com/trailheadlabs/heroku-buildpack-multi.git
  remote: More info: https://devcenter.heroku.com/articles/buildpacks#detection-failure
  remote: 
  remote: Verifying deploy...
  remote: 
  remote: !	Push rejected to kakumamu1.
  remote: 
  To https://git.heroku.com/kakumamu1.git
   ! [remote rejected] master - master (pre-receive hook declined)
  error: failed to push some refs to 'https://git.heroku.com/kakumamu1.git'
```

I have tried to push without the buildpacks and it works, but the website don't have any css and js file.

I am trying many things, and nothing works. I am new to python and heroku.

Thank you.

**Comment by patrys** [comment]
Hey,

Where did you get the `heroku create` command? It lists a long since deprecated buildpack. Saleor now uses two buildpacks and I'm not sure if they can be passed using a single command but you can try the following:

```
$ heroku create kakumamu3 --buildpack https://github.com/mbuchetics/heroku-buildpack-nodejs-grunt.git
$ heroku buildpacks:add --index 1 https://github.com/heroku/heroku-buildpack-python.git
```

**Comment by patrys** [comment]
I've updated the docs to list the same commands.

**Comment by mstfmomin** [comment]
Thank you so much for your quick reply. I followed you and it worked.

However, I still have the same problem that I had when I did not use buildpacks, which is homepage don't have access to any static files like css and Javascript.

Here is the live heroku app of your saleor [Link](https://kakumamu1.herokuapp.com/).

Please let me know know can I access the static file?

> `<html lang="en" class="no-js">
    <head>
        <title>Saleor</title>
        
        <meta charset="utf-8">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <meta name="description" content="">
        <meta name="author" content="Mirumee Software">
        

        <link rel="stylesheet" type="text/css" href="/static/css/storefront.css">`

**Comment by mstfmomin** [comment]
I used this procedure

`git clone https://github.com/mirumee/saleor.git && cd saleor/ && sudo pip install -r requirements.txt && export SECRET_KEY='mysecretkey' && python manage.py migrate
curl -sL https://deb.nodesource.com/setup_4.x | sudo -E bash - && sudo apt-get install -y nodejs && sudo apt-get install nodejs-legacy
npm install && ./node_modules/.bin/grunt
python manage.py runserver

heroku login
heroku create kakumamu1 --buildpack https://github.com/mbuchetics/heroku-buildpack-nodejs-grunt.git
heroku buildpacks:add --index 1 https://github.com/heroku/heroku-buildpack-python.git
heroku addons:add heroku-postgresql
heroku addons:add heroku-redis
heroku config:set SECRET_KEY='mysecretkey'
heroku config:set ALLOWED_HOSTS='.herokuapp.com'
heroku run python manage.py migrate
git push heroku master
heroku run python manage.py createsuperuser
heroku open`

**Comment by patrys** [comment]
Can you try with:

```
$ heroku run python manage.py collectstatic
```

**Comment by mstfmomin** [comment]
Here what I have done.

`heroku run python manage.py collectstatic`

And, I get the following output:
```
mam@mam-Lenovo-Z51-70:~/test/saleor$ heroku run python manage.py collectstatic
Running python manage.py collectstatic on ⬢ kakumamu3... up, run.6276
/app/.heroku/python/lib/python3.5/site-packages/selectable/forms/fields.py:27: RemovedInDjango110Warning: `BaseAutoCompleteField._has_changed` method should be renamed `has_changed`.
  class BaseAutoCompleteField(forms.Field):


You have requested to collect static files at the destination
location as specified in your settings:

    /app/static

This will overwrite existing files!
Are you sure you want to do this?

Type 'yes' to continue, or 'no' to cancel: yes
Copying '/app/saleor/static/js/dashboard.js'
Copying '/app/saleor/static/js/storefront.js'
Copying '/app/saleor/static/fonts/Roboto-Bold.woff'
Copying '/app/saleor/static/fonts/Roboto-Regular.ttf'
Copying '/app/saleor/static/fonts/glyphicons-halflings-regular.woff2'
Copying '/app/saleor/static/fonts/Roboto-Bold.ttf'
Copying '/app/saleor/static/fonts/glyphicons-halflings-regular.svg'
Copying '/app/saleor/static/fonts/glyphicons-halflings-regular.woff'
Copying '/app/saleor/static/fonts/Roboto-Medium.woff'
Copying '/app/saleor/static/fonts/Material-Design-Icons.svg'
Copying '/app/saleor/static/fonts/Material-Design-Icons.ttf'
Copying '/app/saleor/static/fonts/Roboto-Light.woff'
Copying '/app/saleor/static/fonts/Material-Design-Icons.woff2'
Copying '/app/saleor/static/fonts/Roboto-Thin.ttf'
Copying '/app/saleor/static/fonts/Roboto-Regular.woff'
Copying '/app/saleor/static/fonts/Roboto-Thin.woff2'
Copying '/app/saleor/static/fonts/Roboto-Medium.ttf'
Copying '/app/saleor/static/fonts/Material-Design-Icons.eot'
Copying '/app/saleor/static/fonts/fontawesome-webfont.eot'
Copying '/app/saleor/static/fonts/fontawesome-webfont.svg'
Copying '/app/saleor/static/fonts/Roboto-Bold.woff2'
Copying '/app/saleor/static/fonts/glyphicons-halflings-regular.eot'
Copying '/app/saleor/static/fonts/Roboto-Thin.woff'
Copying '/app/saleor/static/fonts/Material-Design-Icons.woff'
Copying '/app/saleor/static/fonts/fontawesome-webfont.ttf'
Copying '/app/saleor/static/fonts/Roboto-Light.ttf'
Copying '/app/saleor/static/fonts/fontawesome-webfont.woff2'
Copying '/app/saleor/static/fonts/fontawesome-webfont.woff'
Copying '/app/saleor/static/fonts/Roboto-Light.woff2'
Copying '/app/saleor/static/fonts/glyphicons-halflings-regular.ttf'
Copying '/app/saleor/static/fonts/Roboto-Medium.woff2'
Copying '/app/saleor/static/fonts/FontAwesome.otf'
Copying '/app/saleor/static/fonts/Roboto-Regular.woff2'
Copying '/app/saleor/static/css/dashboard.css.map'
Copying '/app/saleor/static/css/storefront.css'
Copying '/app/saleor/static/css/dashboard.css'
Copying '/app/saleor/static/css/storefront.css.map'
```

No when I got to [https://kakumamu3.herokuapp.com/](https://kakumamu3.herokuapp.com/), and try to see the source code.

```
<html lang="en" class="no-js">
    <head>
        <title>Saleor</title>
        
        <meta charset="utf-8">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <meta name="description" content="">
        <meta name="author" content="Mirumee Software">
        

        <link rel="stylesheet" type="text/css" href="/static/css/storefront.css">
```

Here the css link:
`<link rel="stylesheet" type="text/css" href="/static/css/storefront.css">`

I click there and found the following error:

```
Page not found (404)
Request Method:	GET
Request URL:	https://kakumamu1.herokuapp.com/static/css/storefront.css
Using the URLconf defined in saleor.urls, Django tried these URL patterns, in this order:
^ ^$ [name='home']
^account/
^admin/
^cart/
^checkout/
^dashboard/
^order/
^products/
^profile/
^selectable/
^sitemap\.xml$ [name='django.contrib.sitemaps.views.sitemap']
^process/(?P<token>[0-9a-z]{8}-[0-9a-z]{4}-[0-9a-z]{4}-[0-9a-z]{4}-[0-9a-z]{12})/$ [name='process_payment']
^process/(?P<variant>[a-z-]+)/$ [name='static_process_payment']
^media/(?P<path>.*)$
The current URL, static/css/storefront.css, didn't match any of these.
You're seeing this error because you have DEBUG = True in your Django settings file. Change that to False, and Django will display a standard 404 page.
```

**Comment by mstfmomin** [comment]
I thin the problem is `app/static` and `/static`.

I have tried several stackoverflow suggestion, where they wanted to change the urls.py.
```
if not settings.DEBUG:
    urlpatterns += patterns('',
        (r'^static/(?P<path>.*)$', 'django.views.static.serve', {'document_root': settings.STATIC_ROOT}),
    )
```

But no luck.

I have tried to find out the file and it exist.

```
mam@mam-Lenovo-Z51-70:~/test/saleor$ heroku run ls -l saleor/static
Running ls -l saleor/static on ⬢ kakumamu3... up, run.4533
total 36
drwx------ 2 u36409 dyno 4096 Jun 10 04:38 css
drwx------ 3 u36409 dyno 4096 Jun 10 04:38 fonts
drwx------ 2 u36409 dyno 4096 Jun 10 04:33 images
drwx------ 2 u36409 dyno 4096 Jun 10 04:33 img
drwx------ 2 u36409 dyno 4096 Jun 10 04:38 js
drwx------ 4 u36409 dyno 4096 Jun 10 04:33 js_src
drwx------ 2 u36409 dyno 4096 Jun 10 04:33 less
drwx------ 2 u36409 dyno 4096 Jun 10 04:33 placeholders
drwx------ 4 u36409 dyno 4096 Jun 10 04:33 scss

```

**Comment by mstfmomin** [comment]
Is there any clean tutorial which actually worked on heroku? eCommerce site should be easy to deploy and edit for non-programming person.

**Comment by patrys** [comment]
After `collectstatic` you should see everything copied to `/app/static/`. Judging from your output the collection process works. At this point `uwsgi` takes care of serving files.

I suppose the problem is that `collectstatic` was not run during app build time. Running it outside of the buildpack is only good for testing as changes made to disk outside of buildpack are not permanent. I'll go through the instructions and make sure they are up to date. In the meantime I suggest you try to use the automated deployment utilising `app.json` file.

**Comment by mstfmomin** [comment]
`collectstatic` ran during app build time.
```
remote:      $ python manage.py collectstatic --noinput
remote:        /app/.heroku/python/lib/python3.5/site-packages/selectable/forms/fields.py:27: RemovedInDjango110Warning: `BaseAutoCompleteField._has_changed` method should be renamed `has_changed`.
remote:          class BaseAutoCompleteField(forms.Field):
remote:        110 static files copied to '/app/static'.
```

> In the meantime I suggest you try to use the automated deployment utilising `app.json` file.

Please tell me how can I do that.

**Comment by patrys** [comment]
You can use the button that is in the readme (make sure it points to your repository and not Mirumee). I think it's also possible to point Heroku's web wizard to your git repository but can't provide instructions as I'm on my phone right now.

I'll look into your issues once I reach my office.

**Comment by mstfmomin** [comment]
I will request you to clone the saleor form git and deploy it to heroku by yourself. Finally, write us the procedure that you have followed.

Saleor will be a very good tool for IoT based emommerce, if you can make it easy for your customers. I really like it and thank you for your support.

**Comment by mstfmomin** [comment]
### I found a way.

I deployed the code from [http://getsaleor.com/](http://getsaleor.com/). Then used the following command from heroku > personal app > deploy.

`heroku git:clone -a kakumamu2016`

### Terminal
```
Cloning into 'kakumamu2016'...
warning: You appear to have cloned an empty repository.
Checking connectivity... done.
```
### Clone original saleor repo.

`git clone https://github.com/mirumee/saleor.git`
`cd saleor`
`copy` all content from saleor folder
paste them to your heroku app which you have deployed from saleor website.

```
git add .
git commit -am "make it better"
git push heroku master
```

### Create super user

`heroku run python manage.py createsuperuser`

**Comment by Mitaanshu-Agarwal** [comment]
@mstfmomin thanks for the solution. 
I am currently doing exactly as you said, and then I tried updating the aws keys in my settings.py and then commited the same. But nothing is happening.

Is there any command that I need to run to get the aws s3 storage functionality running?
